package com.example.workouttracker.ui.theme

import androidx.compose.ui.graphics.Color

/* ===== Базовые оттенки (синие/бирюзовые для стандартных тем) ===== */
val PrimaryBlue   = Color(0xFF0A6ABF)
val PrimaryLight  = Color(0xFF69B7FF)
val SecondaryTeal = Color(0xFF007D8C)

/* ====== LIGHT ====== */
val LightPrimary            = PrimaryBlue
val LightOnPrimary          = Color(0xFFFFFFFF)
val LightPrimaryContainer   = Color(0xFFE6F2FF)
val LightOnPrimaryContainer = Color(0xFF0A3058)
val LightSecondary          = SecondaryTeal
val LightOnSecondary        = Color(0xFFFFFFFF)
val LightBackground         = Color(0xFFF7FAFD)
val LightSurface            = Color(0xFFFFFFFF)
val LightOnSurface          = Color(0xFF1A1A1A)
val LightSurfaceVariant     = Color(0xFFE9F1FA)
val LightOutline            = Color(0xFFB6C3CF)
val LightError              = Color(0xFFB00020)
val LightOnError            = Color(0xFFFFFFFF)

/* ====== DARK ====== */
val DarkPrimary             = Color(0xFF8CC9FF)
val DarkOnPrimary           = Color(0xFF01243F)
val DarkPrimaryContainer    = Color(0xFF053055)
val DarkOnPrimaryContainer  = Color(0xFFBFE1FF)
val DarkSecondary           = Color(0xFF7DE4F0)
val DarkOnSecondary         = Color(0xFF00363D)
val DarkBackground          = Color(0xFF0E1319)
val DarkSurface             = Color(0xFF171C24)
val DarkOnSurface           = Color(0xFFE6EDF5)
val DarkSurfaceVariant      = Color(0xFF243141)
val DarkOutline             = Color(0xFF8392A3)
val DarkError               = Color(0xFFCF6679)
val DarkOnError             = Color(0xFF000000)

/* ====== WARM (тёплая, коричнево-янтарная) — LIGHT ====== */
val WarmLightPrimary            = Color(0xFF8D5A2B)  // карамель/латте
val WarmLightOnPrimary          = Color(0xFFFFFFFF)
val WarmLightPrimaryContainer   = Color(0xFFFFE7CA)
val WarmLightOnPrimaryContainer = Color(0xFF3B240E)
val WarmLightSecondary          = Color(0xFFB08968)
val WarmLightOnSecondary        = Color(0xFF2B1B10)
val WarmLightBackground         = Color(0xFFFFFBF7)
val WarmLightSurface            = Color(0xFFFFFEFC)
val WarmLightOnSurface          = Color(0xFF201A16)
val WarmLightSurfaceVariant     = Color(0xFFF2E6DB)
val WarmLightOutline            = Color(0xFFC9B8A8)
val WarmLightError              = Color(0xFFBA1B1B)
val WarmLightOnError            = Color(0xFFFFFFFF)

/* ====== WARM — DARK ====== */
val WarmDarkPrimary             = Color(0xFFFFC38A)
val WarmDarkOnPrimary           = Color(0xFF44260E)
val WarmDarkPrimaryContainer    = Color(0xFF5A3417)
val WarmDarkOnPrimaryContainer  = Color(0xFFFFE7CA)
val WarmDarkSecondary           = Color(0xFFE6C3A5)
val WarmDarkOnSecondary         = Color(0xFF3B2B1F)
val WarmDarkBackground          = Color(0xFF191311)
val WarmDarkSurface             = Color(0xFF211A17)
val WarmDarkOnSurface           = Color(0xFFEBDDD0)
val WarmDarkSurfaceVariant      = Color(0xFF3A2E25)
val WarmDarkOutline             = Color(0xFFB79E89)
val WarmDarkError               = Color(0xFFFFB4A9)
val WarmDarkOnError             = Color(0xFF680003)

/* ====== FUCHSIA — LIGHT ====== */
val FuchsiaLightPrimary            = Color(0xFFD000B3)
val FuchsiaLightOnPrimary          = Color(0xFFFFFFFF)
val FuchsiaLightPrimaryContainer   = Color(0xFFFFD6F2)
val FuchsiaLightOnPrimaryContainer = Color(0xFF3A0030)
val FuchsiaLightSecondary          = Color(0xFF6E40C9)
val FuchsiaLightOnSecondary        = Color(0xFFFFFFFF)
val FuchsiaLightBackground         = Color(0xFFFFF7FC)
val FuchsiaLightSurface            = Color(0xFFFFFFFF)
val FuchsiaLightOnSurface          = Color(0xFF1B1218)
val FuchsiaLightSurfaceVariant     = Color(0xFFF5E6F1)
val FuchsiaLightOutline            = Color(0xFFCEB5C9)
val FuchsiaLightError              = Color(0xFFBA1B1B)
val FuchsiaLightOnError            = Color(0xFFFFFFFF)

/* ====== FUCHSIA — DARK ====== */
val FuchsiaDarkPrimary             = Color(0xFFFF9AE8)
val FuchsiaDarkOnPrimary           = Color(0xFF4F0043)
val FuchsiaDarkPrimaryContainer    = Color(0xFF6B0060)
val FuchsiaDarkOnPrimaryContainer  = Color(0xFFFFD6F2)
val FuchsiaDarkSecondary           = Color(0xFFB89BFF)
val FuchsiaDarkOnSecondary         = Color(0xFF1F1147)
val FuchsiaDarkBackground          = Color(0xFF150F14)
val FuchsiaDarkSurface             = Color(0xFF1B151B)
val FuchsiaDarkOnSurface           = Color(0xFFEFE1EC)
val FuchsiaDarkSurfaceVariant      = Color(0xFF2D2230)
val FuchsiaDarkOutline             = Color(0xFFC5A9BF)
val FuchsiaDarkError               = Color(0xFFFFB4A9)
val FuchsiaDarkOnError             = Color(0xFF680003)



/* ====== GREEN — LIGHT ====== */
val GreenLightPrimary            = Color(0xFF2E7D32)
val GreenLightOnPrimary          = Color(0xFFFFFFFF)
val GreenLightPrimaryContainer   = Color(0xFFC8E6C9)
val GreenLightOnPrimaryContainer = Color(0xFF08210B)
val GreenLightSecondary          = Color(0xFF558B2F)
val GreenLightOnSecondary        = Color(0xFFFFFFFF)
val GreenLightBackground         = Color(0xFFF4FFF5)
val GreenLightSurface            = Color(0xFFFFFFFF)
val GreenLightOnSurface          = Color(0xFF102116)
val GreenLightSurfaceVariant     = Color(0xFFE1F3E3)
val GreenLightOutline            = Color(0xFF9BB59E)
val GreenLightError              = Color(0xFFBA1B1B)
val GreenLightOnError            = Color(0xFFFFFFFF)

/* ====== GREEN — DARK ====== */
val GreenDarkPrimary             = Color(0xFFA5D6A7)
val GreenDarkOnPrimary           = Color(0xFF00310E)
val GreenDarkPrimaryContainer    = Color(0xFF174322)
val GreenDarkOnPrimaryContainer  = Color(0xFFC8E6C9)
val GreenDarkSecondary           = Color(0xFFC5E1A5)
val GreenDarkOnSecondary         = Color(0xFF22300A)
val GreenDarkBackground          = Color(0xFF0B130D)
val GreenDarkSurface             = Color(0xFF151D17)
val GreenDarkOnSurface           = Color(0xFFE2EDE3)
val GreenDarkSurfaceVariant      = Color(0xFF243428)
val GreenDarkOutline             = Color(0xFF8FA892)
val GreenDarkError               = Color(0xFFFFB4A9)
val GreenDarkOnError             = Color(0xFF680003)

/* ====== BLUE-PURPLE — LIGHT ====== */
val BluePurpleLightPrimary            = Color(0xFF3949AB)
val BluePurpleLightOnPrimary          = Color(0xFFFFFFFF)
val BluePurpleLightPrimaryContainer   = Color(0xFFE3E6FF)
val BluePurpleLightOnPrimaryContainer = Color(0xFF0A1040)
val BluePurpleLightSecondary          = Color(0xFF7E57C2)
val BluePurpleLightOnSecondary        = Color(0xFFFFFFFF)
val BluePurpleLightBackground         = Color(0xFFF7F6FF)
val BluePurpleLightSurface            = Color(0xFFFFFFFF)
val BluePurpleLightOnSurface          = Color(0xFF121424)
val BluePurpleLightSurfaceVariant     = Color(0xFFE2E0F5)
val BluePurpleLightOutline            = Color(0xFFB5B3D5)
val BluePurpleLightError              = Color(0xFFBA1B1B)
val BluePurpleLightOnError            = Color(0xFFFFFFFF)

/* ====== BLUE-PURPLE — DARK ====== */
val BluePurpleDarkPrimary             = Color(0xFFB0BEFF)
val BluePurpleDarkOnPrimary           = Color(0xFF151B64)
val BluePurpleDarkPrimaryContainer    = Color(0xFF232D80)
val BluePurpleDarkOnPrimaryContainer  = Color(0xFFE3E6FF)
val BluePurpleDarkSecondary           = Color(0xFFD1C1FF)
val BluePurpleDarkOnSecondary         = Color(0xFF2A174F)
val BluePurpleDarkBackground          = Color(0xFF0E0F1A)
val BluePurpleDarkSurface             = Color(0xFF171826)
val BluePurpleDarkOnSurface           = Color(0xFFE4E3F5)
val BluePurpleDarkSurfaceVariant      = Color(0xFF2B2D42)
val BluePurpleDarkOutline             = Color(0xFF9C9ABD)
val BluePurpleDarkError               = Color(0xFFFFB4A9)
val BluePurpleDarkOnError             = Color(0xFF680003)

/* ====== AURORA — LIGHT (особенная неоновая) ====== */
val AuroraLightPrimary            = Color(0xFF00C4B4) // неоновый бирюзовый
val AuroraLightOnPrimary          = Color(0xFF001F1C)
val AuroraLightPrimaryContainer   = Color(0xFFC2FFF4)
val AuroraLightOnPrimaryContainer = Color(0xFF00201B)
val AuroraLightSecondary          = Color(0xFF8E4DFF) // фиолетовый акцент
val AuroraLightOnSecondary        = Color(0xFFFFFFFF)
val AuroraLightBackground         = Color(0xFF0A1014)
val AuroraLightSurface            = Color(0xFF0F1720)
val AuroraLightOnSurface          = Color(0xFFE3FDFC)
val AuroraLightSurfaceVariant     = Color(0xFF17212B)
val AuroraLightOutline            = Color(0xFF5ADFD0)
val AuroraLightError              = Color(0xFFBA1B1B)
val AuroraLightOnError            = Color(0xFFFFFFFF)

/* ====== AURORA — DARK ====== */
val AuroraDarkPrimary             = Color(0xFF00E5CC)
val AuroraDarkOnPrimary           = Color(0xFF00201B)
val AuroraDarkPrimaryContainer    = Color(0xFF00423A)
val AuroraDarkOnPrimaryContainer  = Color(0xFFC2FFF4)
val AuroraDarkSecondary           = Color(0xFFCF9BFF)
val AuroraDarkOnSecondary         = Color(0xFF2E004C)
val AuroraDarkBackground          = Color(0xFF05070B)
val AuroraDarkSurface             = Color(0xFF060A10)
val AuroraDarkOnSurface           = Color(0xFFCCFFF7)
val AuroraDarkSurfaceVariant      = Color(0xFF0F1820)
val AuroraDarkOutline             = Color(0xFF69EDE0)
val AuroraDarkError               = Color(0xFFFFB4A9)
val AuroraDarkOnError             = Color(0xFF680003)

